packages:
  - 'apps/**'
  - 'packages/**'
  - 'scripts/**'
  # - '../patchwork/packages/**'
  - '!**/build/**'
  - '!**/dist/**'

catalog:
  '@aprovan/patchwork-compiler': ^0.1.0
  '@aprovan/patchwork-editor': ^0.1.0
  '@aprovan/bobbin': ^0.1.0
  '@aprovan/patchwork-image-shadcn': ^0.1.0
